name: sigclient-tools-release
on:
  push:
    branches:
      - 'main'
jobs:
  sigclient-tool-binaries:
    runs-on: ubuntu-latest
    environment: build-environment
    permissions:
      id-token: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      -
        name: Package SigClient
        run: |
          ./package-sigclient.sh -b s3://sigscalr-releases -p linux/amd64,linux/arm64
  sigclient-docker-images:
    runs-on: ubuntu-latest
    environment: build-environment
    permissions:
      id-token: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      -   
        name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.PUBLIC_ECR_REPO }}
          registry-type: public
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Get Version number
        id: get-version
        run: |
          TAG=$(cat SIGCLIENT_VERSION)
          echo "TAG=$TAG" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - 
        name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: sigclient
          tags: |
            type=raw,value=${{ env.TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.PUBLIC_ECR_REPO }}/${{ steps.metadata.outputs.tags }}

