issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA6002:"

linters:
  enable:
    - exhaustive

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

run:
  build-tags:
    - e2e_all
