issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA6002:"

linters:
  enable:
    - exhaustive
    - importas

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/siglens/siglens/pkg/utils
        alias: ""
      - pkg: github.com/siglens/siglens/pkg/segment/utils
        alias: segutils

run:
  build-tags:
    - e2e_all
