steps:

  - name: golang:1.19
    entrypoint: /bin/bash
    args:
      - -c
      - |
        make build && \
        ./siglens --config server.yaml


timeout: 3600s

options:
 defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
