steps:

  - name: golang:1.21-alpine3.18
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        make build && \
        ./siglens --config server.yaml & \
        sleep 10 && \
        cd tools/sigclient && \
        go run main.go functional -d http://localhost:8081/elastic -f functionalQueries/functionalQueries.yml -q localhost:5122


timeout: 3600s

options:
 defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
