name: benchmark_ingest_query

on:
    push:
      branches:
        - 'sigClient_save_query_uuids'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: siglens-develop:latest

    - name: Run install.sh script
      run: |
        chmod +x ./install.sh
        ./install.sh
      env:
        DOCKER_IMAGE_NAME: "siglens-develop:latest"
        DOCKER_COMPOSE_YAML: "./docker-compose.yml"
        USE_LOCAL_DOCKER_COMPOSE: true
        TERM: xterm

    - name: Verify server is running
      run: |
        echo "Waiting for server to start..."
        sleep 5
        if ! curl --silent http://localhost:5122 | head -n 30; then
          echo "Server did not start within 5 seconds"
          exit 1
        fi
    - name: Run E2E Test
      run: |
        cd tools/sigclient
        go run main.go ingest esbulk -n 1 -g benchmark-ingest-query -d http://localhost:8081/elastic -t 1000000 -p 500