name: develop-e2e-install-test

on:
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: siglens-develop:latest

    - name: Run install_with_docker.sh script
      run: |
        chmod +x ./install_with_docker.sh
        ./install_with_docker.sh
      env:
        DOCKER_IMAGE_NAME: "siglens-develop:latest"
        DOCKER_COMPOSE_YAML: "./docker-compose.yml"
        USE_LOCAL_DOCKER_COMPOSE: true
        TERM: xterm

    - name: Verify server is running
      run: |
        echo "Waiting for server to start..."
        sleep 5
        if ! curl --silent http://localhost:5122 | head -n 30; then
          echo "Server did not start within 5 seconds"
          exit 1
        fi
    - name: Run E2E Test
      run: |
        cd tools/sigclient
        go run main.go query esbulk -d http://localhost:5122 -f ../../cicd/sample_log_dataset_queries.csv