name: Nightly-Longer-Functional-Test

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at midnight EST (UTC-5)
  workflow_dispatch:  # Allows manual trigger as well

jobs:
  Clickbench-10M-Test:
    runs-on: [self-hosted, Linux, X64]
    name: Clickbench 10M
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: |
          sudo yum install python3-pip
          pip install requests
      - uses: actions/checkout@v3
      - name: Build Siglens
        run: make build
      - name: Run Siglens
        run: |
            ./siglens --config server.yaml > output.log 2>&1 &
      - name: Get Data 1
        run: |
            cd tools/clickbench
            wget https://github.com/siglens/pub-datasets/releases/download/5m-cb/splithits_1.tar
            tar -xzvf splithits_1.tar
            rm splithits_1.tar
      - name: Send Data 1
        run: |
            python3 send_datamulti.py
            rm splithits_1
      - name: Restart Siglens
        run: |
            pkill siglens
            sleep 10
            ./siglens --config server.yaml > output2.log 2>&1 &
      - name: Run Clickbench Test
        run: |
            sleep 5  # Wait for Siglens to start
            cd tools/sigclient
            go run main.go clickBench -d localhost:5122
      - name: Print server execution logs for ingestion # For crashes
        if: always()
        run: |
            cat output.log
      - name: Print server execution logs for query # For crashes
        if: always()
        run: |
            cat output2.log
      - name: Print siglens logs
        if: always()
        run: |
            cat logs/siglens.log

