name: release-deploy.yml

on:
  push:

jobs:
  deploy:
    name: "Deploy Siglens"
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Configuration
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/playground
          chmod 600 ~/.ssh/playground
          cat >>~/.ssh/config <<END
          Host playground
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/playground
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PG_SSH_USER }}
          SSH_KEY: ${{ secrets.PG_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PG_HOST }}
      - name: Export Environment Variables and Execute Install Script
        run: |
          ssh playground 'export TERM=xterm; curl -L https://siglens.com/install.sh | sh > /dev/null 2>&1'
      - name: Verify Server Start
        run: |
          sleep 5
          if ! curl --silent http://localhost:5122 | head -n 30; then
            echo "Server did not start within 5 seconds"
            exit 1
          fi