name: release-deploy.yml

on:
  workflow_run:
    workflows: ["siglens-docker-release"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: "Deploy Siglens"
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Configuration
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/playground
          chmod 600 ~/.ssh/playground
          cat >>~/.ssh/config <<END
          Host playground
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/playground
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PG_SSH_USER }}
          SSH_KEY: ${{ secrets.PG_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PG_HOST }}
      - name: Check path
        run: |
          ssh playground 'echo $PATH'
      - name: Export Environment Variables and Execute Install Script
        run: |
          ssh -tt playground 'bash -lc "export TERM=xterm; export SERVERNAME=${{ secrets.PG_SERVERNAME }}; cd ${{ secrets.PG_DOCKER_INSTALL_PATH }}; curl -L https://siglens.com/install.sh | sh"'
      - name: Verify Server Start
        run: |
          sleep 5
          ssh playground 'export TERM=xterm; if ! curl --silent http://localhost:5122 | head -n 30; then echo "Server did not start within 5 seconds"; exit 1; fi'
      - name: Start Sigclient
        run: |
          ssh playground 'export TERM=xterm; sudo nohup ${{ secrets.PG_LOAD_TEST_PATH }} ingest esbulk -b 1 -d http://localhost:8081/elastic -g dynamic-user -n 1 -c > /dev/null 2>${{ secrets.PG_INGEST_LOG_FILE }} &'