name: test-deploy-using k3s-helm
on:
  push:
    branches:
      - 'test_with_helm'
jobs:
#   siglens-docker:
# upload assets
    e2e-k3s:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup golang
                uses: actions/setup-go@v4
                with:
                    go-version: "1.21"
            -   name: Create a k3s cluster
                uses: AbsaOSS/k3d-action@v2
                with:
                    cluster-name: "siglens"
                    # args: >-
                    #     -p "8081:8081@agent:0:direct"
                    #     -p "5122:5122@agent:0:direct"
                    #     -p "2222:2222@agent:0:direct"
                    #     --agents 1
                    #     --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

            -   name: Deploy the app
                run: |
                    helm repo add siglens https://siglens.github.io/charts
                    # create platform namespace
                    kubectl create ns platform

                    # installing using helm
                    helm install siglens siglens/siglens -n platform \
                    --wait \
                    --timeout 10m0s \
                    --set query.service.type=LoadBalancer 
                    # get pods, services and the container images
                    kubectl get pods -n platform
                    kubectl get svc -n platform

            -   name: Display tunnel URL and IP Address of the worker node
                id: get-subdomain
                run: |
                    subdomain="siglens-latest"
                    echo "URL for tunnelling: https://$subdomain.loca.lt"
                    echo "subdomain=$subdomain" >> $GITHUB_OUTPUT
                    worker_ip="$(curl -4 -s ipconfig.io/ip)"
                    echo "Worker node IP address: $worker_ip"
            
            -   name: Start tunnel
                env:
                    SUBDOMAIN: ${{ steps.get-subdomain.outputs.subdomain }}
                run: |
                    npm install -g localtunnel
                    host=$(kubectl get svc -n platform | grep siglens-query-svc | tr -s ' ' | cut -d" " -f4)
                    port=$(kubectl get svc -n platform | grep siglens-query-svc | tr -s ' ' | cut -d" " -f5 | cut -d":" -f1)
                    lt -p $port -l $host -s $SUBDOMAIN
                            
            
            
